version: "3"

services:
  gunicorn:
    build:
      args:
        BUILD_TARGET: ${BUILD_TARGET:-release}
      context: gunicorn
      dockerfile: Dockerfile
    image: app_gunicorn:${BUILD_TARGET:-latest}  
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASS: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    profiles:
      - release
      - testing
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    image: app_nginx:latest
    ports:
      - "80:80"
    depends_on:
      - gunicorn
    profiles:
      - release
  postgres:
    image: postgis/postgis:13-3.4-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # ports:
    #   - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
