name: Build, test and push images

on:    
  workflow_dispatch:
    inputs:
      image-tag:
        type: string
        required: true
        description: Image tag for pushed image
        default: latest

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build and test images
        env:
          BUILD_TARGET: testing
        run: |
          docker-compose build gunicorn
          docker-compose up --detach
          docker-compose run --rm gunicorn
          docker-compose down
  # build:
  #   name: Build and push
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v4

  #     - name: Build and push images to Amazon ECR
  #       run: |
  #         docker build --build-arg BUILD_TARGET=testing --tag gunicorn:testing gunicorn/
  #         docker run --rm gunicorn:testing
  #         docker build --build-arg BUILD_TARGET=release --tag gunicorn:release gunicorn/
  #         docker run --rm gunicorn:release