name: Build and push images

on:
  push:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: Github environment
      image-tag:
        type: string
        required: true
        description: Image tag for pushed image
        default: latest

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # - repository: nginx
          #   path: ./nginx
          - repository: gunicorn
            path: ./gunicorn

    environment: ${{ inputs.environment }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build and push images to Amazon ECR
        env:
          REPOSITORY: ${{ matrix.repository }}
          IMAGE_TAG: ${{ inputs.image-tag }}
        run: |
          docker build --build-arg BUILD_TARGET=testing --tag $REPOSITORY:testing ${{ matrix.path }}
          docker run --rm $REPOSITORY:testing
          docker build --build-arg BUILD_TARGET=release --tag $REPOSITORY:$IMAGE_TAG ${{ matrix.path }}
          docker run --rm $REPOSITORY:$IMAGE_TAG